### PR TITLE
Fix broken links in Social Side Bar

### PR DESCRIPTION
**Pull request by vtexier**
* Fix Bugs link
* Fix RSS link

### CODE REVIEW

**Review by M5oul — APPROVED** [review]
Tested.

**Comment by M5oul** [comment]
It have been deployed on the server.
But, It is not fixed.

**Comment by thiswillbeyourgithub** [comment]
I still get a 404 when clicking "RSS" on the right pannel

**Comment by c-geek** [comment]
I don't know why, but my commits did revert the changes made by @vtexier. Sorry. Fixed.

**Pull request merged**
